version: "3.8"

services:
  postgres:
    container_name: runes-postgres
    build: 
      context: ../postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Qwerty123
    healthcheck:
      test: 'psql -U divination forecasts -c "SELECT 1"'
      timeout: 10s
      interval: 5s
      start_period: 10s
      retries: 5

  api:
    build: 
      context: ../forecast-backend
    container_name: runes-api
    ports:
      - "8000:8000"
    volumes:
      - ./forecast-backend:/app
      - /app/dist
    depends_on:
      postgres:
        condition: service_healthy
  
  client:
    build:
      context: ../forecast-client
    container_name: runes-client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ../forecast-react:/app
  