version: "3.8"

services:
  postgres:
    container_name: runes-postgres
    build: 
      context: ../runes-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Qwerty123
    volumes:
      - ../runes-postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: 'psql -U divination forecasts -c "SELECT 1"'
      timeout: 10s
      interval: 5s
      start_period: 10s
      retries: 5

  api:
    build: 
      context: ../runes-api
    container_name: runes-api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  
  client:
    build:
      context: ../runes-client
      dockerfile: Dockerfile.prod
    container_name: runes-client
    ports:
      - "3000:3000"